sitewomen/sitewomen/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework import routers
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

from sitewomen import settings
from women.views import *

# class MyCustomRouter(routers.SimpleRouter):
#     routers = [
#         routers.Route(
#             url=r'^{prefix}$',
#             mapping={'get': 'list'},
#             name='{basename}-list',
#             detail=False,
#             initkwargs={'suffix': 'List'}),
#         routers.Route(
#             url=r'^{prefix}/{lookup}$',
#             mapping={'get': 'retrieve'},
#             name='{basename}-detail',
#             detail=True,
#             initkwargs={'suffix': 'Detail'})]

#router = routers.DefaultRouter() # класс роутеров формирует список маршрутов
# router = MyCustomRouter() # класс роутеров формирует список маршрутов
# router.register(r'ladies',WomenViewSet) # GET /api/v1/ladies/women-list/ имя маршрута берется из имени модели
# # router.register(r'women',WomenViewSet, basename = 'men') # GET /api/v1/women/men-list/ имя маршрута сменяется
# # модели
# print(router.urls)

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('api/v1/', include(router.urls)),
    path('', include('women.urls')),
    path('api/v1/drf-auth/', include('rest_framework.urls')),
    path('api/v1/women', WomenAPIList.as_view()),
    path('api/v1/women/<int:pk>', WomenAPIUpdate.as_view()),
    path('api/v1/womendelete/<int:pk>', WomenAPIDestroy.as_view()),
    path('api/v1/auth/', include('djoser.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),    # jwt token
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),   # jwt token
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),      # jwt token
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    # маршрут к медиафайлам в режиме отладки. В боевом режиме сервер сам знает путь
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found
admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Известные женщины мира"

sitewomen/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetDoneView, \
    PasswordResetView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

PasswordChangeView

appname = 'users'
urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),

    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        email_template_name='users/password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset'),

    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')), name='password_reset_confirm'),

    path('password-reset/complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),


    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
]

sitewomen/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from datetime import datetime
from django.forms import SelectDateWidget


class LoginUserForm(AuthenticationForm):
    # username = forms.CharField(label= 'Логин',
    #                            widget=forms.TextInput(attrs={'class': 'form-input'}))
    # password = forms.CharField(label= 'Пароль',
    #                            widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model() # привязка к стандартной модели пользователя
        fields = ['username','password'] # указывает поля для отображения в форме

class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин')
    password1 = forms.CharField(label='Пароль',widget=forms.PasswordInput())
    password2 = forms.CharField(label='Повтор пароля',widget=forms.PasswordInput())

    class Meta:
        model= get_user_model()
        fields = ['username', 'email','first_name','last_name','password1','password2',]
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия'
        }
        widgets = {
                   'email': forms.TextInput(attrs={'class': 'form-input'}),
                   'first_name': forms.TextInput(attrs={'class': 'form-input'}),
                   'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }
    # def clean_password2(self):
    #     cd = self.cleaned_data
    #     if cd['password'] != cd['password2']:
    #         raise forms.ValidationError('Пароли не совпадают')
    #     return cd['password']

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('Такой e-mail уже существует')
        return email

class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label= 'Логин',widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(disabled=True, label= 'E-mail',widget=forms.TextInput(attrs={'class': 'form-input'}))
    this_year = datetime.now().year
    date_birth = forms.DateTimeField(widget=SelectDateWidget(years=tuple(range(this_year-100, this_year-5))))
    class Meta:
        model= get_user_model()
        fields = ['photo', 'username', 'email','date_birth','first_name','last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия'
        }
        widgets = {
                   'first_name': forms.TextInput(attrs={'class': 'form-input'}),
                   'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }

class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label='старый пароль', widget=forms.PasswordInput(attrs={'class':'form-input'}))
    new_password1 = forms.CharField(label='новый пароль', widget=forms.PasswordInput(attrs={'class':'form-input'}))
    new_password2 = forms.CharField(label='повторите пароль', widget=forms.PasswordInput(attrs={'class':'form-input'}))

sitewomen/users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}

<h1> Авторизация </h1>

<form method="post">
    {% csrf_token %}
    <input type="hidden" name = "next" value = {{ next }}>
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
        <div class="form-error">{{f.errors }}</div>
    {% endfor %}
<p> <button type="submit"> Войти </button></p>
    
<p><a href="{% url 'users:password_reset' %}"> Забыл пароль? </a></p>
</form>

{% endblock %}

sitewomen/users/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block content %}

<h1> Ваш пароль успешно изменен! </h1>

<p>Вы успешно изменили пароль. <a href="{% url 'users:profile' %}"> Вернуться в профиль</a></p>

{% endblock %}

sitewomen/users/templates/users/password_change_form.html
{% extends 'base.html' %}

{% block content %}

<h1> Изменение пароля </h1>

<form method="post">
    {% csrf_token %}
    <input type="hidden" name = "next" value = {{ next }}>
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
        <div class="form-error">{{f.errors }}</div>
    {% endfor %}
<p> <button type="submit"> Изменить пароль </button></p>

</form>


{% endblock %}

sitewomen/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}

<h1> Ваш пароль успешно изменен! </h1>

<p>Вы успешно изменили пароль. Используйте его для <a href="{% url 'users:login' %}"> входа в систему</a></p>

{% endblock %}

sitewomen/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}

<h1> Новый пароль </h1>

<form method="post">
    {% csrf_token %}
    <input type="hidden" name = "next" value = {{ next }}>
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
        <div class="form-error">{{f.errors }}</div>
    {% endfor %}
<p> <button type="submit"> Сохранить </button></p>

</form>

{% endblock %}

sitewomen/users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h1> Сброс пароля </h1>
<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

sitewomen/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

sitewomen/users/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block content %}

<h1> Восстановление пароля </h1>

<form method="post">
    {% csrf_token %}
    <input type="hidden" name = "next" value = {{ next }}>
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
        <div class="form-error">{{f.errors }}</div>
    {% endfor %}
<p> <button type="submit"> Сбросить по e-mail </button></p>

</form>

{% endblock %}

sitewomen/users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}

<h1> Профиль </h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% if user.photo %}
    <p><img src="{{user.photo.url}}" width="200" height="250">
    {% else %}
    <p><img src=" {{default_image}} ">
    {% endif %}
    <input type="hidden" name = "next" value = {{ next }}>
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
        <div class="form-error">{{f.errors }}</div>
    {% endfor %}
<p> <button type="submit"> Сохранить </button></p>

</form>

<p><a href="{% url 'users:password_change' %}"> Сменить пароль </a></p>

{% endblock %}

sitewomen/users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}

<h1> Регистрация </h1>

<form method="post">
    {% csrf_token %}
    <input type="hidden" name = "next" value = {{ next }}/>
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
        <div class="form-error">{{f.errors }}</div>
    {% endfor %}
    <p> <button type="submit"> Зарегистрироваться </button></p>

</form>

{% endblock %}

sitewomen/users/templates/users/register_done.html
{% extends 'base.html' %}

{% block content %}

<h1> Добро пожаловать! </h1>

<p> Вы успешно зарегистрировались! Для входа необходимо авторизоваться по </p>

<a href="{% url 'users:login' %}"> ссылке </a>

{% endblock %}